# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # Rust/Cargo package ecosystem
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
     dev-dependencies:
        dependency-type: "development"
    assignees:
      - "deeprave"
    reviewers:
      - "deeprave"
  - package-ecosystem: "github-actions" # GitHub Actions ecosystem
    directory: "/" # Location of workflow files
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
