[package]
name = "repostats"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[package.metadata]
plugin_api_version = 20250727

[dependencies]
clap = { version = "4.5", features = ["derive", "string"] }
gix = "0.73"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
colored = "3.0"
dirs = "6.0"
atty = "0.2"
unicode-segmentation = "1.12.0"
log = "0.4.27"
flexi_logger = "0.31"
chrono = "0.4.41"
async-trait = "0.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "time", "fs"] }
thiserror = "2.0"

[build-dependencies]
chrono = "0.4"
toml = "0.9"
