[project]
name = "repostats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cc-sessions>=0.2.7",
    "tiktoken>=0.11.0",
]
